/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.Statement;
import java.lang.String;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shivani Chauhan
 */
public class addmember extends javax.swing.JFrame {

    /**
     * Creates new form addmember
     */
    public addmember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        join = new javax.swing.JTextField();
        course = new javax.swing.JTextField();
        duefee = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        duration = new javax.swing.JTextField();
        totalfee = new javax.swing.JTextField();
        View = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Add New Student");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 10, 270, 40);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(200, 120, 130, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(200, 160, 130, 30);

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address);
        address.setBounds(200, 200, 130, 30);
        jPanel1.add(mobile);
        mobile.setBounds(200, 250, 130, 30);

        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });
        jPanel1.add(join);
        join.setBounds(200, 300, 130, 30);
        jPanel1.add(course);
        course.setBounds(200, 350, 130, 30);

        duefee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duefeeActionPerformed(evt);
            }
        });
        jPanel1.add(duefee);
        duefee.setBounds(200, 500, 130, 30);

        save.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(320, 600, 70, 25);

        duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationActionPerformed(evt);
            }
        });
        jPanel1.add(duration);
        duration.setBounds(200, 400, 130, 30);

        totalfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalfeeActionPerformed(evt);
            }
        });
        jPanel1.add(totalfee);
        totalfee.setBounds(200, 450, 130, 30);

        View.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        View.setText("view");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        jPanel1.add(View);
        View.setBounds(420, 600, 70, 25);

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Student  Name", "Student Address", "Student mobile", "Join Date", "Course Name", "Course Duration", "Total Fee", "Due Fee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(360, 110, 910, 430);

        jLabel2.setText("Student id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 120, 130, 30);

        jLabel3.setText("Student name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 170, 130, 20);

        jLabel4.setText("Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 210, 46, 20);

        jLabel5.setText("Mobile number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 260, 110, 16);

        jLabel6.setText("join date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 310, 50, 16);

        jLabel7.setText("course name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 360, 74, 16);

        jLabel8.setText("course duration");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 410, 89, 16);

        jLabel9.setText("Total fee");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 460, 51, 16);

        jLabel10.setText("Due fee");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 510, 44, 16);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 600, 63, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinActionPerformed

    private void duefeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duefeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duefeeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        //save data to mysql
        String sid = id.getText();
        String saddress = address.getText();
        String sname = name.getText();
        String smobile = mobile.getText();
        String sjoin = join.getText();
        String scourse = course.getText();
        String sduration = duration.getText();
        String total = totalfee.getText();
        String due = duefee.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo","root","root");
            String query = "insert into student values('"+sid+"','"+sname+"','"+saddress+"','"+smobile+"','"+sjoin+"','"+scourse+"','"+sduration+"','"+total+"','"+due+"')";
            Statement st =  conn.createStatement();
            int ra = st.executeUpdate(query);
            if(ra > 0){
                JOptionPane.showMessageDialog(this,"Insert sucessfully");
            }else{
                JOptionPane.showMessageDialog(this,"Insertion failed");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            //return null;
        }
    }//GEN-LAST:event_saveActionPerformed

    private void durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationActionPerformed

    private void totalfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalfeeActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/demo","root","root");
            String query = "Select * from student";
            Statement st =  conn.createStatement();
            ResultSet rs = st.executeQuery(query);
             DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
             model.setRowCount(0);
            while(rs.next()){
               
                
                Object x[] ={rs.getString("student_id"),rs.getString("student_name"), rs.getString("student_address"), rs.getString("student_mobile_no"), rs.getDate(5), rs.getString("course_name"),rs.getString("course_duration"), rs.getInt("total_fee"),rs.getInt("due_fee")};
                model.addRow(x);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(addmember.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ViewActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    menu m=new menu();
    m.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton View;
    private javax.swing.JTextField address;
    private javax.swing.JTextField course;
    private javax.swing.JTextField duefee;
    private javax.swing.JTextField duration;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField join;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JButton save;
    private javax.swing.JTextField totalfee;
    // End of variables declaration//GEN-END:variables
}
